""" Banana """

module(
    name = "hello_arm64",
    version = "1.0",
)

bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.14")
bazel_dep(name = "aspect_rules_lint", version = "2.1.0")
bazel_dep(name = "supply_chain_tools", version = "0.0.1")
bazel_dep(name = "package_metadata", version = "0.0.7")
bazel_dep(name = "rules_python", version = "1.0.0")
bazel_dep(name = "googletest", version = "1.15.2")
bazel_dep(name = "rules_shell", version = "0.6.1")
bazel_dep(name = "abseil-cpp", version = "20240722.0.bcr.1")
bazel_dep(name = "rules_go", version = "0.60.0")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    python_version = "3.11",
)
use_repo(python, "python_3_11")

register_toolchains("@python_3_11//:all")

bazel_dep(name = "buildifier_prebuilt", version = "6.4.0", dev_dependency = True)
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    commit = "abb61a688167623088f8768cc9264798df6a9d10",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
)

bazel_dep(name = "toolchains_llvm", version = "1.6.0")

# Configure and register the toolchain.
llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    llvm_version = "19.1.6",
)

sysroot = use_repo_rule("@toolchains_llvm//toolchain:sysroot.bzl", "sysroot")

sysroot(
    name = "org_chromium_sysroot_linux_amd64",
    sha256 = "47c02efd920c7f9c6b98b1498443170aa6102507d0672af5e794070833ef7454",
    urls = ["https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/4c00ba2ad61ca7cc39392f192aa39420e086777c/debian_bullseye_amd64_sysroot.tar.xz"],
)

sysroot(
    name = "org_chromium_sysroot_linux_arm64",
    sha256 = "902d1a40a5fd8c3764a36c8d377af5945a92e3d264c6252855bda4d7ef81d3df",
    urls = ["https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/41a6c8dec4c4304d6509e30cbaf9218dffb4438e/debian_bullseye_arm64_sysroot.tar.xz"],
)

llvm.sysroot(
    name = "llvm_toolchain",
    label = "@org_chromium_sysroot_linux_amd64//sysroot",
    targets = ["linux-x86_64"],
)
llvm.sysroot(
    name = "llvm_toolchain",
    label = "@org_chromium_sysroot_linux_arm64//sysroot",
    targets = ["linux-aarch64"],
)
use_repo(llvm, "llvm_toolchain")
use_repo(llvm, "llvm_toolchain_llvm")

register_toolchains("@llvm_toolchain//:all")

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_file(
    name = "jq_linux_amd64",
    downloaded_file_path = "jq",
    executable = True,
    sha256 = "5942c9b0934e510ee61eb3e30273f1b3fe2590df93933a93d7c58b81d19c8ff5",
    urls = ["https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64"],
)

http_file(
    name = "jq_linux_arm64",
    downloaded_file_path = "jq",
    executable = True,
    sha256 = "4dd2d8a0661df0b22f1bb9a1f9830f06b6f3b8f7d91211a1ef5d7c4f06a8b4a5",
    urls = ["https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-arm64"],
)

http_file(
    name = "jq_macos_amd64",
    downloaded_file_path = "jq",
    executable = True,
    sha256 = "4155822bbf5ea90f5c79cf254665975eb4274d426d0709770c21774de5407443",
    urls = ["https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-macos-amd64"],
)

http_file(
    name = "jq_macos_arm64",
    downloaded_file_path = "jq",
    executable = True,
    sha256 = "0bbe619e663e0de2c550be2fe0d240d076799d6f8a652b70fa04aea8a8362e8a",
    urls = ["https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-macos-arm64"],
)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "grcov_linux_amd64",
    build_file_content = "exports_files(['grcov'])",
    sha256 = "80df5b760e901d56b28515584311137ffcd332eb7375b452b22a9538851d0993",
    urls = ["https://github.com/mozilla/grcov/releases/download/v0.10.5/grcov-x86_64-unknown-linux-gnu.tar.bz2"],
)

http_archive(
    name = "grcov_linux_arm64",
    build_file_content = "exports_files(['grcov'])",
    sha256 = "4f1d93bc6a87b824f393f55ceb09c61ea560bb193a27adf6b2d0e4bac0a2ff62",
    urls = ["https://github.com/mozilla/grcov/releases/download/v0.10.5/grcov-aarch64-unknown-linux-gnu.tar.bz2"],
)

http_archive(
    name = "grcov_macos_amd64",
    build_file_content = "exports_files(['grcov'])",
    sha256 = "02c3161743c0ee8fa1e72dfe7a37e2009608aee010827067b101a0ccc72dd344",
    urls = ["https://github.com/mozilla/grcov/releases/download/v0.10.5/grcov-x86_64-apple-darwin.tar.bz2"],
)

http_archive(
    name = "grcov_macos_arm64",
    build_file_content = "exports_files(['grcov'])",
    sha256 = "4d92a519a950adc1ca4a62be8d717eab160fec5406ee7bcad55bf830c366853e",
    urls = ["https://github.com/mozilla/grcov/releases/download/v0.10.5/grcov-aarch64-apple-darwin.tar.bz2"],
)

http_file(
    name = "cpplint",
    downloaded_file_path = "cpplint.py",
    executable = True,
    sha256 = "4be787d36ac081b42f82b41307833723bfb30cf7e5dd72b5fa2af458529b0eb9",
    urls = ["https://raw.githubusercontent.com/cpplint/cpplint/2.0.0/cpplint.py"],
)

http_archive(
    name = "ripgrep_linux_amd64",
    build_file_content = "exports_files(['rg'])",
    sha256 = "1c9297be4a084eea7ecaedf93eb03d058d6faae29bbc57ecdaf5063921491599",
    strip_prefix = "ripgrep-15.1.0-x86_64-unknown-linux-musl",
    urls = ["https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz"],
)

http_archive(
    name = "ripgrep_linux_arm64",
    build_file_content = "exports_files(['rg'])",
    sha256 = "2b661c6ef508e902f388e9098d9c4c5aca72c87b55922d94abdba830b4dc885e",
    strip_prefix = "ripgrep-15.1.0-aarch64-unknown-linux-gnu",
    urls = ["https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-aarch64-unknown-linux-gnu.tar.gz"],
)

http_archive(
    name = "ripgrep_macos_amd64",
    build_file_content = """
package(default_visibility = ["//visibility:public"])
exports_files(["ripgrep-15.1.0-x86_64-apple-darwin/rg"])
alias(name = "rg", actual = "ripgrep-15.1.0-x86_64-apple-darwin/rg")
""",
    sha256 = "64811cb24e77cac3057d6c40b63ac9becf9082eedd54ca411b475b755d334882",
    urls = ["https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-apple-darwin.tar.gz"],
)

http_archive(
    name = "ripgrep_macos_arm64",
    build_file_content = "exports_files(['rg'])",
    sha256 = "378e973289176ca0c6054054ee7f631a065874a352bf43f0fa60ef079b6ba715",
    strip_prefix = "ripgrep-15.1.0-aarch64-apple-darwin",
    urls = ["https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-aarch64-apple-darwin.tar.gz"],
)

http_archive(
    name = "dprint_linux_amd64",
    build_file_content = "exports_files(['dprint'])",
    sha256 = "581e44d57631498edfed6baad5dd77d832116a12c94dd6fb394045ed40af18ea",
    urls = ["https://github.com/dprint/dprint/releases/download/0.45.0/dprint-x86_64-unknown-linux-gnu.zip"],
)

http_archive(
    name = "dprint_linux_arm64",
    build_file_content = "exports_files(['dprint'])",
    sha256 = "45af380a82a65ebe173de25329093fc2e27cf64f3aeef9e39f723873b12fba7f",
    urls = ["https://github.com/dprint/dprint/releases/download/0.45.0/dprint-aarch64-unknown-linux-gnu.zip"],
)

http_archive(
    name = "dprint_macos_amd64",
    build_file_content = "exports_files(['dprint'])",
    sha256 = "6df01e0357049ad3bc62bbd2f60c9c448bd747b650ebf20f7ab5a38cefd36b44",
    urls = ["https://github.com/dprint/dprint/releases/download/0.45.0/dprint-x86_64-apple-darwin.zip"],
)

http_archive(
    name = "dprint_macos_arm64",
    build_file_content = "exports_files(['dprint'])",
    sha256 = "cf23ab2785ca25f27ed5ca5127663dfe0131ae146d0b8d5159b06e0694ad74ac",
    urls = ["https://github.com/dprint/dprint/releases/download/0.45.0/dprint-aarch64-apple-darwin.zip"],
)
