load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "greet",
    srcs = ["greet.cc"],
    hdrs = ["greet.h"],
    deps = [
        "//third_party/mock_lib",
        "@abseil-cpp//absl/strings",
    ],
)

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [":greet"],
)

cc_test(
    name = "greet_test",
    srcs = ["greet_test.cc"],
    deps = [
        ":greet",
        "@googletest//:gtest_main",
    ],
)

