#!/bin/bash
set -euo pipefail

# This script sets up the development environment.
# It bootstraps Bazel (bazelisk), optionally builds tools, and generates the .envrc cache.
# Usage: ./tools/setup_dev_env.sh [--no-build]

BUILD_TOOLS=true
for arg in "$@"; do
    if [ "$arg" == "--no-build" ]; then
        BUILD_TOOLS=false
    fi
done

# Determine OS/Arch for cache segregation (must match .envrc logic)
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
if [ "$ARCH" = "x86_64" ]; then
    BAZEL_ARCH="amd64"
elif [ "$ARCH" = "aarch64" ]; then
    BAZEL_ARCH="arm64"
else
    echo "Unsupported architecture: $ARCH" >&2
    exit 1
fi

CACHE_DIR=".cache/${OS}_${BAZEL_ARCH}"
CACHE_FILE="$CACHE_DIR/bazel_path_cache"
mkdir -p "$CACHE_DIR/bin"

# 1. Bootstrap Bazel (bazelisk)
if [ ! -f "$CACHE_DIR/bin/bazel" ]; then
    echo "Local Bazel not found. Bootstrapping bazelisk to $CACHE_DIR/bin/..." >&2
    BAZELISK_VERSION="v1.20.0"
    URL="https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-${OS}-${BAZEL_ARCH}"
    curl -L -o "$CACHE_DIR/bin/bazel" "$URL"
    chmod +x "$CACHE_DIR/bin/bazel"
fi

# Ensure our local bazel is in PATH for this script
export PATH="$PWD/$CACHE_DIR/bin:$PATH"

# Define toolchain targets
targets=(
    "//tools/ripgrep"
    "//tools/jq"
    "//tools/grcov"
    "//tools/dprint"
    "@llvm_toolchain//:bin/clangd"
    "@python_3_12//:python3"
)

# 2. Build tools (optional)
if [ "$BUILD_TOOLS" = true ]; then
    echo "Building toolchain targets..." >&2
    bazel build "${targets[@]}"
fi

echo "Generating toolchain path cache..." >&2

# 3. Generate Cache
# Get output_base
output_base=$(bazel info output_base 2>/dev/null)

CONTENT="# Generated by tools/setup_dev_env.sh - DO NOT EDIT
export BAZEL_OUTPUT_BASE=\"$output_base\"
"

# Batch cquery
query="set(${targets[*]})"

echo "Running bazel cquery..." >&2
cquery_out=$(bazel cquery "$query" --output=starlark --starlark:expr="'\n'.join(['%s|%s' % (str(target.label), f.path) for f in target.files.to_list()])" 2>/dev/null)

if [ -z "$cquery_out" ]; then
    echo "Warning: Failed to query toolchain targets." >&2
else
    # Use a simple string to track seen paths
    seen_paths=""
    echo "Processing paths..." >&2
    
    while IFS='|' read -r label path; do
        if [ -n "$path" ]; then
            if [[ "$path" != /* ]]; then
                path="$output_base/$path"
            fi
            
            if [ ! -e "$path" ] && [ ! -L "$path" ]; then
                echo "Warning: Tool from target '$label' is missing at $path" >&2
            fi
            
            # Canonicalize path using python3 if available
            if command -v python3 >/dev/null; then
                 real_path=$(python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$path")
            else
                 real_path="$path"
            fi
            
            dir=$(dirname "$real_path")
            if [[ "$seen_paths" != *":$dir:"* ]]; then
                CONTENT+="\nPATH_add \"$dir\""
                seen_paths="$seen_paths:$dir:"
            fi
        fi
    done <<< "$cquery_out"
fi

echo -e "$CONTENT" > "$CACHE_FILE"
echo "Done. Cache generated at $CACHE_FILE" >&2

# Touch .envrc to trigger direnv reload
if [ -f ".envrc" ]; then
    touch .envrc
fi

echo "Direnv should reload automatically." >&2
